---
title: "Multivariate - Model Selection"
author: "Carlos Sanchez"
date: "23/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Case where x1 has nothing to do with x2, x3

```{r}
n <- 100 
nosim <- 1000

x1 <- rnorm(n)
x2 <- rnorm(n)
x3 <- rnorm(n)

betas <- sapply(1 : nosim, function(i){
  y <- x1 + rnorm(n, sd = .3)
  c(coef(lm(y ~ x1))[2],
  coef(lm(y ~ x1 + x2))[2],
  coef(lm(y ~ x1 + x2 + x3))[2])
})

round(apply(betas, 1, sd), 5)
```

```{r}
n <- 100
nosim <- 1000

x1 <- rnorm(n)
x2 <- x1/sqrt(2) + rnorm(n) /sqrt(2)
x3 <- x1 * 0.95 + rnorm(n) * sqrt(1 - 0.95^2)

betas <- sapply(1 : nosim, function(i){
  y <- x1 + rnorm(n, sd = .3)
  c(coef(lm(y ~ x1))[2],
  coef(lm(y ~ x1 + x2))[2],
coef(lm(y ~ x1 + x2 + x3))[2])
})

round(apply(betas, 1, sd), 5)
```


```{r}
library(car)

fit <- lm(Fertility ~ ., data = swiss)
vif(fit)          #Variance Inflation Factor
sqrt(vif(fit))
```


#Nested models

```{r}
fit1 <- lm(Fertility ~ Agriculture, data = swiss)
fit3 <- update(fit, Fertility ~ Agriculture + Examination + Education)
fit5 <- update(fit, Fertility ~ Agriculture + Examination + Education + Catholic + Infant.Mortality)

anova(fit1, fit3, fit5)
```



